.TH UMIT 1 "August 07, 2008"

.SH NAME
umit \- network tool and port scanner

.SH SYNOPSIS
\fBumit\fP

.SH DESCRIPTION
\fBumit\fP scans the hosts in your network discovering open ports and the
services and operating systems that they are running.
.PP
With \fBumit\fP, you have all the power provided by \fBnmap\fP
through its regular command line interface, and a lot more, in a highly usable
and portable graphical interface. A regular user will be able to
construct powerful scans with \fBumit\fP's command creatiop wizards.

.SH FILES
.TP
~/.umit
Stores configuration settings for \fBumit\fP.

.SH BUGS
Please report bugs at http://trac.umitproject.org.

.SH SEE ALSO
http://www.umitproject.org

.SH AUTHORS
Adriano Monteiro Marques <adriano@umitproject.org>

Cleber Rodrigues <cleber.gnu@gmail.com>

Frederico Silva Ribeiro <ribeiro.fsilva@gmail.com>

Guilherme Polo <ggpolo@gmail.com>


This manual page was written by Luis A. Bastião Silva <luis.kop@gmail.com>.

